### ISSUE TITLE
Problem running the test

### ISSUE THREAD

**Issue by ericntd** [react-component/form-validation#16]
I have a lot of problems running `npm install`:  
```
│ ├─┬ gh-pages@0.3.1
│ │ ├── UNMET DEPENDENCY async@0.2.9
│ │ ├── UNMET DEPENDENCY graceful-fs@2.0.1
│ │ ├── UNMET DEPENDENCY lodash@~2.4.1
│ │ ├── UNMET DEPENDENCY q@~1.0.1
│ │ ├── UNMET DEPENDENCY q-io@~1.11.0
│ │ └── UNMET DEPENDENCY wrench@1.5.1
│ ├─┬ glob@5.0.15 invalid
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@3.0.0
│ │ │ └─┬ brace-expansion@1.1.1
│ │ │   ├── balanced-match@0.2.1
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.3.2
│ │ │ └── wrappy@1.0.1
│ │ └── path-is-absolute@1.0.0
├─┬ karma-sauce-launcher@0.2.14
│ │ ├── UNMET DEPENDENCY q@~0.9.6
│ │ ├── UNMET DEPENDENCY sauce-connect-launcher@~0.11.1
│ │ ├── UNMET DEPENDENCY saucelabs@~0.1.0
│ │ └── UNMET DEPENDENCY wd@~0.3.4
├─┬ saucelabs-runner@2.2.4
│ │ ├── UNMET DEPENDENCY async@~0.9.0
│ │ ├── UNMET DEPENDENCY debug@~2.1.0
│ │ ├── UNMET DEPENDENCY modulex-promise@~1.1.3
│ │ ├── UNMET DEPENDENCY modulex-util@~1.1.4
│ │ ├── UNMET DEPENDENCY sauce-tunnel@1.x
│ │ └── UNMET DEPENDENCY wd@~0.3.11
npm ERR! extraneous: glob@4.0.6 /Users/eric/tmp/form-validation/node_modules/glob
npm ERR! missing: async@0.2.9, required by gh-pages@0.3.1
npm ERR! missing: graceful-fs@2.0.1, required by gh-pages@0.3.1
npm ERR! missing: lodash@~2.4.1, required by gh-pages@0.3.1
npm ERR! missing: q@~1.0.1, required by gh-pages@0.3.1
npm ERR! missing: q-io@~1.11.0, required by gh-pages@0.3.1
npm ERR! missing: wrench@1.5.1, required by gh-pages@0.3.1
npm ERR! invalid: glob@5.0.15 /Users/eric/tmp/form-validation/node_modules/rc-tools/node_modules/glob
npm ERR! missing: wd@~0.3.4, required by karma-sauce-launcher@0.2.14
npm ERR! missing: sauce-connect-launcher@~0.11.1, required by karma-sauce-launcher@0.2.14
npm ERR! missing: q@~0.9.6, required by karma-sauce-launcher@0.2.14
npm ERR! missing: saucelabs@~0.1.0, required by karma-sauce-launcher@0.2.14
npm ERR! missing: async@~0.9.0, required by saucelabs-runner@2.2.4
npm ERR! missing: debug@~2.1.0, required by saucelabs-runner@2.2.4
npm ERR! missing: modulex-promise@~1.1.3, required by saucelabs-runner@2.2.4
npm ERR! missing: modulex-util@~1.1.4, required by saucelabs-runner@2.2.4
npm ERR! missing: sauce-tunnel@1.x, required by saucelabs-runner@2.2.4
npm ERR! missing: wd@~0.3.11, required by saucelabs-runner@2.2.4
```
And then `npm start` is definitely not working:  
```
➜  form-validation git:(master) npm start

> rc-form-validation@2.5.0 start /Users/eric/tmp/form-validation
> rc-server

/Users/eric/tmp/form-validation/node_modules/rc-server/lib/index.js:39
  app.get('/tests/runner.html', function* () {
                                        ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/eric/tmp/form-validation/node_modules/rc-server/bin/start.js:3:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! rc-form-validation@2.5.0 start: `rc-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rc-form-validation@2.5.0 start script 'rc-server'.
npm ERR! This is most likely a problem with the rc-form-validation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rc-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls rc-form-validation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eric/tmp/form-validation/npm-debug.log
```
Could you advise?

**Comment by benjycui** [comment]
Please upgrade you Node.js

**Comment by benjycui** [comment]
https://nodejs.org/en/
